### ISSUE TITLE
NPE in com.pablissimo.sonar.TsLintParserImpl.parse(TsLintParserImpl.java:26)

### ISSUE THREAD

**Issue by jimjaeger** [Pablissimo/SonarTsPlugin#145]
During local execution the following NPE occured.

ERROR: Error during SonarQube Scanner execution
java.lang.NullPointerException
        at com.pablissimo.sonar.TsLintParserImpl.parse(TsLintParserImpl.java:26)
        at com.pablissimo.sonar.TsLintSensor.execute(TsLintSensor.java:104)
        at org.sonar.batch.sensor.SensorWrapper.analyse(SensorWrapper.java:57)
        at org.sonar.batch.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:58)
        at org.sonar.batch.phases.SensorsExecutor.execute(SensorsExecutor.java:50)
        at org.sonar.batch.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:83)
        at org.sonar.batch.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:192)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
        at org.sonar.batch.scan.ProjectScanContainer.scan(ProjectScanContainer.java:241)
        at org.sonar.batch.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:236)
        at org.sonar.batch.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:234)
        at org.sonar.batch.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:226)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
        at org.sonar.batch.task.ScanTask.execute(ScanTask.java:47)
        at org.sonar.batch.task.TaskContainer.doAfterStart(TaskContainer.java:86)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
        at org.sonar.batch.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:106)
        at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:119)
        at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:63)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
        at com.sun.proxy.$Proxy0.execute(Unknown Source)
        at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:233)
        at org.sonarsource.scanner.api.EmbeddedScanner.runAnalysis(EmbeddedScanner.java:151)
        at org.sonarsource.scanner.cli.Main.runAnalysis(Main.java:123)
        at org.sonarsource.scanner.cli.Main.execute(Main.java:77)
        at org.sonarsource.scanner.cli.Main.main(Main.java:61)

**Comment by jimjaeger** [comment]
was an issue of an older version

**Comment by santhuhappy24** [comment]
i have similar issue as above.
Below is the error

15:28:37.384 DEBUG: Sensors : NoSonar Sensor -> ProcessRuleSensor -> Coverage Report Import -> Coverage Report Import -> Unit Test Results Import -> XmlFileSensor -> Analyzer for "php.ini" files -> Zero Coverage Sensor -> Code Colorizer Sensor -> CPD Block Indexer
15:28:37.385 INFO: Sensor NoSonar Sensor [php]
15:28:37.385 INFO: Sensor NoSonar Sensor [php] (done) | time=0ms
15:28:37.385 INFO: Sensor ProcessRuleSensor [tibcobw6]
15:28:37.774 DEBUG: 'TestTibcoProject.module/Processes/testtibcoproject/module/Process.bwp' generated metadata  with charset 'UTF-8'
15:28:37.887 DEBUG: 'TestTibcoProject.module/Processes/testtibcoproject/module/SubProcess.bwp' generated metadata  with charset 'UTF-8'
15:28:37.935 INFO: ------------------------------------------------------------------------
15:28:37.935 INFO: EXECUTION FAILURE
15:28:37.935 INFO: ------------------------------------------------------------------------
15:28:37.935 INFO: Total time: 5.480s
15:28:38.093 INFO: Final Memory: 44M/142M
15:28:38.093 INFO: ------------------------------------------------------------------------
15:28:38.093 ERROR: Error during SonarQube Scanner execution
java.lang.NullPointerException
	at com.tibco.businessworks6.sonar.plugin.sensor.ProcessRuleSensor.getSharedResourcesCount(ProcessRuleSensor.java:389)
	at com.tibco.businessworks6.sonar.plugin.sensor.ProcessRuleSensor.processMetrics(ProcessRuleSensor.java:246)
	at com.tibco.businessworks6.sonar.plugin.sensor.AbstractSensor.analyse(AbstractSensor.java:112)
	at com.tibco.businessworks6.sonar.plugin.sensor.AbstractRuleSensor.analyse(AbstractRuleSensor.java:119)
	at org.sonar.scanner.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:57)
	at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:49)
	at org.sonar.scanner.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:74)
	at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:175)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:143)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:128)
	at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:262)
	at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:257)
	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:247)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:143)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:128)
	at org.sonar.scanner.task.ScanTask.execute(ScanTask.java:47)
	at org.sonar.scanner.task.TaskContainer.doAfterStart(TaskContainer.java:86)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:143)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:128)
	at org.sonar.scanner.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:118)
	at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:117)
	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
	at com.sun.proxy.$Proxy0.execute(Unknown Source)
	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:233)
	at org.sonarsource.scanner.api.EmbeddedScanner.runAnalysis(EmbeddedScanner.java:151)
	at org.sonarsource.scanner.cli.Main.runAnalysis(Main.java:123)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:77)
	at org.sonarsource.scanner.cli.Main.main(Main.java:61)
15:28:38.093 DEBUG: Execution getVersion
15:28:38.096 DEBUG: Execution stop
ERROR: SonarQube scanner exited with non-zero code: 1
Finished: FAILURE
Please do the need the needful.

Regards,

Santhosh

**Comment by nixel2007** [comment]
@santhuhappy24 your error is not from the TS plugin. Search for the something releated to com.tibco.businessworks6
