### ISSUE TITLE
what is the correct path for tslintpath?

### ISSUE THREAD

**Issue by OneCyrus** [Pablissimo/SonarTsPlugin#34]
I'm trying to get the 0.4-pre to work. But I don't get the plugin to find TSLint. I'm not sure what the tslintpath expects.

i tried a lot of different paths and escaping methods, but nothing seems to work. E.g. an example which i tried. (i'm running this as a build job in TFS)

sonar.ts.tslintpath: C:\\WINDOWS\\system32\\config\\systemprofile\\AppData\\Roaming\\npm\\node_modules\\tslint\\bin\\tslint

> 2016-06-02T15:43:44.1737708Z 17:43:44.095 ERROR - TsLint Err: module.js:327
2016-06-02T15:43:44.1737708Z 17:43:44.095 ERROR - TsLint Err:     throw err;
2016-06-02T15:43:44.1737708Z 17:43:44.095 ERROR - TsLint Err:     ^
2016-06-02T15:43:44.1737708Z 17:43:44.095 ERROR - TsLint Err:
2016-06-02T15:43:44.1737708Z 17:43:44.095 ERROR - TsLint Err: Error: Cannot find module 'C:\WINDOWS\system32\config\systemprofile\AppData\Roaming\npm\node_modules\tslint\bin\tslint'
2016-06-02T15:43:44.1737708Z 17:43:44.095 ERROR - TsLint Err:     at Function.Module._resolveFilename (module.js:325:15)
2016-06-02T15:43:44.1737708Z 17:43:44.095 ERROR - TsLint Err:     at Function.Module._load (module.js:276:25)
2016-06-02T15:43:44.1737708Z 17:43:44.095 ERROR - TsLint Err:     at Function.Module.runMain (module.js:441:10) 
2016-06-02T15:43:44.1737708Z 17:43:44.095 ERROR - TsLint Err:     at startup (node.js:139:18)
2016-06-02T15:43:44.1737708Z 17:43:44.095 ERROR - TsLint Err:     at node.js:968:3

when running manually running "node.exe C:\\WINDOWS\\system32\\config\\systemprofile\\AppData\\Roaming\\npm\\node_modules\\tslint\\bin\\tslint" it works fine. Any ideas?

**Comment by Pablissimo** [comment]
You've got something vaguely sensible looking there, so my guess would be it's a permissions issue (I can't access %system32%\config without going through a UAC prompt - what's the user the build controller's running as? Does it have access to that path?

**Comment by OneCyrus** [comment]
thanks! it was really a permission issue. it's running as "network service" in a VSO build agent.
