### ISSUE TITLE
Increase performance

### ISSUE THREAD

**Issue by NikitaEgorov** [Pablissimo/SonarTsPlugin#35]
Please pass chunk of files to TSLint
or run nodejs once and call tslint in one nodejs process like gulp

**Comment by rdkleine** [comment]
bump

**Comment by NikitaEgorov** [comment]
```js
const Linter = require("tslint");
const fs = require("fs");

const fileName = "Specify file name";
const configuration = {
    rules: {
        "variable-name": true,
        "quotemark": [true, "double"]
    }
};
const options = {
    formatter: "json",
    configuration: configuration,
    rulesDirectory: "customRules/",
    formattersDirectory: "customFormatters/"
};

const fileContents = fs.readFileSync(fileName, "utf8");
const linter = new Linter(fileName, fileContents, options);
const result = linter.lint();
```

**Comment by Pablissimo** [comment]
Yep, running multiple files into it in one bash seems like a good shout (to the point I don't know why it's not currently doing it). Shouldn't be too hard...

**Comment by Pablissimo** [comment]
Had a bash at this this morning - it'll try and batch files to process into bundles such that the command line generated is <= 4096 bytes long (so you'll get potentially a couple hundred files being batched together) which should be quicker, though it's not gone through a lot of testing yet.

Try pulling https://github.com/Pablissimo/SonarTsPlugin/tree/issue35 down and seeing how you get on (binary attached) but YMMV.

[sonar-typescript-plugin-0.5-SNAPSHOT.zip](https://github.com/Pablissimo/SonarTsPlugin/files/321844/sonar-typescript-plugin-0.5-SNAPSHOT.zip)

**Comment by NikitaEgorov** [comment]
error]com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated array at line 2 column 2 path $[0]
 
2016-06-23T09:17:30.0659943Z ##[error]at com.google.gson.Gson.fromJson(Gson.java:820)
 
2016-06-23T09:17:30.0659943Z ##[error]at com.google.gson.Gson.fromJson(Gson.java:770)
 
2016-06-23T09:17:30.0669709Z ##[error]at com.google.gson.Gson.fromJson(Gson.java:719)
 
2016-06-23T09:17:30.0669709Z ##[error]at com.google.gson.Gson.fromJson(Gson.java:691)
 
2016-06-23T09:17:30.0669709Z ##[error]at com.pablissimo.sonar.TsLintParserImpl.parse(TsLintParserImpl.java:12)
 
2016-06-23T09:17:30.0679475Z ##[error]at com.pablissimo.sonar.TsLintSensor.analyse(TsLintSensor.java:107)
 
2016-06-23T09:17:30.0679475Z ##[error]at org.sonar.batch.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:58)
 
2016-06-23T09:17:30.0679475Z ##[error]at org.sonar.batch.phases.SensorsExecutor.execute(SensorsExecutor.java:50)
 
2016-06-23T09:17:30.0689241Z ##[error]at org.sonar.batch.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:83)
 
2016-06-23T09:17:30.0689241Z ##[error]at org.sonar.batch.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:192)
 
2016-06-23T09:17:30.0689241Z ##[error]at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
 
2016-06-23T09:17:30.0699007Z ##[error]at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
 
2016-06-23T09:17:30.0699007Z ##[error]at org.sonar.batch.scan.ProjectScanContainer.scan(ProjectScanContainer.java:241)
 
2016-06-23T09:17:30.0699007Z ##[error]at org.sonar.batch.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:236)
 
2016-06-23T09:17:30.0708773Z ##[error]at org.sonar.batch.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:234)
 
2016-06-23T09:17:30.0708773Z ##[error]at org.sonar.batch.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:226)
 
2016-06-23T09:17:30.0708773Z ##[error]at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
 
2016-06-23T09:17:30.0708773Z ##[error]at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
 
2016-06-23T09:17:30.0708773Z ##[error]at org.sonar.batch.task.ScanTask.execute(ScanTask.java:47)
 
2016-06-23T09:17:30.0718539Z ##[error]at org.sonar.batch.task.TaskContainer.doAfterStart(TaskContainer.java:86)
 
2016-06-23T09:17:30.0728305Z ##[error]at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
 
2016-06-23T09:17:30.0728305Z ##[error]at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
 
2016-06-23T09:17:30.0738071Z ##[error]at org.sonar.batch.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:106)
 
2016-06-23T09:17:30.0738071Z ##[error]at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:119)
 
2016-06-23T09:17:30.0738071Z ##[error]at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:62)
 
2016-06-23T09:17:30.0747837Z ##[error]at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 
2016-06-23T09:17:30.0747837Z ##[error]at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
 
2016-06-23T09:17:30.0747837Z ##[error]at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
 
2016-06-23T09:17:30.0767369Z ##[error]at java.lang.reflect.Method.invoke(Unknown Source)
 
2016-06-23T09:17:30.0767369Z ##[error]at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
 
2016-06-23T09:17:30.0767369Z ##[error]at com.sun.proxy.$Proxy0.execute(Unknown Source)
 
2016-06-23T09:17:30.0767369Z ##[error]at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:240)
 
2016-06-23T09:17:30.0767369Z ##[error]at org.sonarsource.scanner.api.EmbeddedScanner.runAnalysis(EmbeddedScanner.java:151)
 
2016-06-23T09:17:30.0767369Z ##[error]at org.sonarsource.scanner.cli.Main.runAnalysis(Main.java:110)
 
2016-06-23T09:17:30.0777135Z ##[error]at org.sonarsource.scanner.cli.Main.execute(Main.java:72)
 
2016-06-23T09:17:30.0777135Z ##[error]at org.sonarsource.scanner.cli.Main.main(Main.java:60)
 
2016-06-23T09:17:30.0777135Z ##[error]Caused by: com.google.gson.stream.MalformedJsonException: Unterminated array at line 2 column 2 path $[0]
 
2016-06-23T09:17:30.0786901Z ##[error]at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1572)
 
2016-06-23T09:17:30.0786901Z ##[error]at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:478)
 
2016-06-23T09:17:30.0786901Z ##[error]at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:416)
 
2016-06-23T09:17:30.0796667Z ##[error]at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:71)
 
2016-06-23T09:17:30.0796667Z ##[error]at com.google.gson.Gson.fromJson(Gson.java:805)

**Comment by Pablissimo** [comment]
Have you got source files that cause the issue? And what OS/TsList version are in use?

**Comment by NikitaEgorov** [comment]
It's happened with all TS files
NodeJs (v4.2.2) 
TSLint (3.11.0)

**Comment by Pablissimo** [comment]
Thanks - odd, I'm using the same TsLint version and can't repro it but will merge in the pull that tries to fix it and rebuild tonight (or you can do so and see how you get on).

**Comment by Pablissimo** [comment]
Ok, merged the candidate fix in - binary below. If all well, will merge into master at some stage soon (out the next few evenings so unsure when exactly but there we go...). If it doesn't I'm going to need more info to debug as I can't repro.

[sonar-typescript-plugin-0.6-SNAPSHOT.zip](https://github.com/Pablissimo/SonarTsPlugin/files/335777/sonar-typescript-plugin-0.6-SNAPSHOT.zip)

**Comment by NikitaEgorov** [comment]
Thanks all!!!

Build time go down from 6.8min to 2.4min!

**Comment by Pablissimo** [comment]
Love it! Merging.
