### ISSUE TITLE
vsts analysis with no msbuild step

### ISSUE THREAD

**Issue by baywet** [Pablissimo/SonarTsPlugin#54]
Hi,
I'm currently trying to configure SQ TS analysis for a full typescript project. (no .net, working with vs code so no csproj or whatsoever)
The way our CI is configured right now in VSTS is:
- npm install
- SQ begin analysis
- npm run build
- SQ finish analysis
...
I'm currently getting the following error
The SonarQube MSBuild integration failed: SonarQube was unable to collect the required information about your projects.
2016-09-12T18:24:17.9206157Z ##[error]Possible causes:
2016-09-12T18:24:17.9216152Z ##[error]1. The project has not been built - the project must be built in between the begin and end steps
2016-09-12T18:24:17.9216152Z ##[error]2. An unsupported version of MSBuild has been used to build the project. Currently MSBuild 12.0 upwards are supported
2016-09-12T18:24:17.9216152Z ##[error]3. The begin, build or end steps have not all been launched from the same folder

From what I understand this is because I don't have a msbuild step in the process. I'm not quite sure what to do though? should I use other tasks for the analysis? Should I create a dummy C# project? add a msbuild step that does nothing?

**Comment by baywet** [comment]
Should I run the analysis from node ? https://tonicdev.com/npm/sonarqube (not a lot of documentation on this one)

**Comment by Pablissimo** [comment]
So the only way I've gotten the MSBuild integration to work is to have a dummy .csproj file for it to run off - it doesn't actually need to reference anything, so far as I can tell.

**Comment by baywet** [comment]
Doing so the analysis step doesn't crash but my ts files are not being analyzed. Any idea of what I might have missed?

**Comment by Pablissimo** [comment]
Maybe for VSTS you do need the TypeScript files referenced in the csproj, I've just double-checked my known working example and that's how it appears to be setup. I guess there's nothing stopping you having a custom Node or PowerShell script that kicked off analysis based on your own sonar-project.properties file but you're then not using any of the provided build steps.

You can configure the begin analysis step with additional settings under advanced which may give some guidance:

```/d:sonar.verbose=true /d:sonar.log.level=TRACE```

**Comment by baywet** [comment]
Thanks for your help the debug flag help a lot.
I got it to almost work creating a asp.net mvc 4. ts files have to be referenced and under the project's folder (no simlink or naything else)
Also I'm passing that as argument
`/d:sonar.ts.tslintpath=$(Build.SourcesDirectory)\node_modules\tslint\bin /d:sonar.verbose=true /d:sonar.log.level=TRACE /d:sonar.ts.tslintconfigpath=$(Build.SourcesDirectory)\tsconfig.json /d:sonar.ts.tslintrulesdir=$(Build.SourcesDirectory)\tslint.json`

I have the following error message now so I guess the tslint path is wrong. What should the folder contain?
module.js:341

ERROR: TsLint Err: throw err;

ERROR: TsLint Err: ^

ERROR: TsLint Err:

ERROR: TsLint Err: Error: Cannot find module 'C:\a\1\s\node_modules\tslint\bin'

ERROR: TsLint Err: at Function.Module._resolveFilename (module.js:339:15)

ERROR: TsLint Err: at Function.Module._load (module.js:290:25)

ERROR: TsLint Err: at Function.Module.runMain (module.js:447:10)

ERROR: TsLint Err: at startup (node.js:148:18)

ERROR: TsLint Err: at node.js:405:3

**Comment by Pablissimo** [comment]
You seem to be missing \tslint from the end of your tslint path parameter - needs to be the full path to tslint, not just it's folder



Sent from a mobile device - apologies for any errors as a result


-------- Original message --------

**Comment by baywet** [comment]
Ok I think I got it to work finally
Here is the arguments line 
`/d:sonar.ts.tslintpath=$(Build.SourcesDirectory)\node_modules\tslint /d:sonar.verbose=true /d:sonar.log.level=TRACE /d:sonar.ts.tslintconfigpath=$(Build.SourcesDirectory)\tsconfig.json /d:sonar.ts.tslintrulesdir=$(Build.SourcesDirectory)\tslint.json`

The only thing is I have no code smell entry or bug for typescript files in the report, so either our code is perfect and it works or something is still not working.
Could you please have a look at the log bellow and tell me if everything looks ok.
Here is my log trace
2016-09-13T18:07:53.6049319Z DEBUG: Found sonar.ts.tslintpath Lint path to be 'C:\a\1\s\node_modules\tslint'
2016-09-13T18:07:53.6049319Z DEBUG: Found sonar.ts.tslintconfigpath Lint path to be 'C:\a\1\s\tsconfig.json'
2016-09-13T18:07:53.6049319Z DEBUG: Found sonar.ts.tslintrulesdir Lint path to be 'C:\a\1\s\tslint.json'
2016-09-13T18:07:53.7049310Z DEBUG: Split 23 files into 1 batches for processing
2016-09-13T18:07:53.7049310Z DEBUG: Executing TsLint with command: node "C:\a\1\s\node_modules\tslint" --format json --rules-dir "C:\a\1\s\tslint.json" --config "C:\a\1\s\tsconfig.json" "C:/a/1/s/OceanikOnline.Web/src/app/constants/culture-info.ts" "C:/a/1/s/OceanikOnline.Web/src/app/constants/dictionary-source.ts" "C:/a/1/s/OceanikOnline.Web/src/app/constants/index.ts" "C:/a/1/s/OceanikOnline.Web/src/app/constants/languages-reference.ts" "C:/a/1/s/OceanikOnline.Web/src/app/filters/column-filter.ts" "C:/a/1/s/OceanikOnline.Web/src/app/filters/index.ts" "C:/a/1/s/OceanikOnline.Web/src/app/helpers/http-request.ts" "C:/a/1/s/OceanikOnline.Web/src/app/helpers/index.ts" "C:/a/1/s/OceanikOnline.Web/src/app/helpers/language.helper.ts" "C:/a/1/s/OceanikOnline.Web/src/app/index.ts" "C:/a/1/s/OceanikOnline.Web/src/app/pages/index.ts" "C:/a/1/s/OceanikOnline.Web/src/app/pages/page-redirection.ts" "C:/a/1/s/OceanikOnline.Web/src/app/services/data-mapper.ts" "C:/a/1/s/OceanikOnline.Web/src/app/services/index.ts" "C:/a/1/s/OceanikOnline.Web/src/app/services/sharepoint.service.ts" "C:/a/1/s/OceanikOnline.Web/src/app/settings/index.ts" "C:/a/1/s/OceanikOnline.Web/src/app/settings/********.settings.service.ts" "C:/a/1/s/OceanikOnline.Web/src/app/translation/index.ts" "C:/a/1/s/OceanikOnline.Web/src/app/translation/********.translation.service.ts" "C:/a/1/s/OceanikOnline.Web/src/app/translation/translation.ts" "C:/a/1/s/OceanikOnline.Web/src/app/ui/index.ts" "C:/a/1/s/OceanikOnline.Web/src/app/ui/********-ui.ts" "C:/a/1/s/OceanikOnline.Web/src/app/vendor.ts"
2016-09-13T18:07:54.3079321Z INFO: Sensor com.pablissimo.sonar.TsLintSensor (done) | time=469ms

**Comment by Pablissimo** [comment]
Run the tslint command it claims it is running on the command line and see if any issues appear. It may be that you need to enable all the Typescript rules in the rules profile for your project in the sonarqube admin pages, otherwise unsure. Can't dig in until back from honeymoon I'm afraid!



Sent from a mobile device - apologies for any errors as a result


-------- Original message --------

**Comment by baywet** [comment]
You're on honeymoon? Dude stop watching GitHub and go enjoy it!!!
I ran the same command on my local machine, it came out clear, I guess we need to add more rules that's what it is but everything is working for me now.
Thanks for your help especially in this very special moment of yours, say congrats to the bride for me.
