### ISSUE TITLE
Problem with TSLint and Team Foundation Server Integration

### ISSUE THREAD

**Issue by FourSpotProject** [Pablissimo/SonarTsPlugin#72]
Hi there,

when I run Sonarqube via a Team Foundation Server build it fails with following log message:

```
2016-12-09T12:51:53.0444407Z 13:51:52.935 INFO: Sensor Linting sensor for TypeScript files
2016-12-09T12:51:53.0444407Z 13:51:52.935 DEBUG: Found sonar.ts.tslintpath Lint path to be 'C:\Users\svctestmediaportal\AppData\Roaming\npm\node_modules\tslint\bin\tslint'
2016-12-09T12:51:53.0444407Z 13:51:52.935 DEBUG: Found sonar.ts.tslintconfigpath Lint path to be 'C:\Sonarqube_tslint\tslint.json'
2016-12-09T12:51:53.0444407Z 13:51:52.935 DEBUG: Path sonar.ts.tslintrulesdir not specified, falling back to null
2016-12-09T12:51:53.0444407Z 13:51:52.935 DEBUG: Using a temporary path for TsLint output: C:\TfsAgent\_work\1\.sonarqube\out\.sonar\.sonartmp\7956119935354822877.tmp
2016-12-09T12:51:53.0444407Z 13:51:52.935 DEBUG: Split 542 files into 17 batches for processing
2016-12-09T12:51:53.1694489Z 13:51:52.951 DEBUG: Executing TsLint with command: node C:\Users\svctestmediaportal\AppData\Roaming\npm\node_modules\tslint\bin\tslint --format json --out C:\TfsAgent\_work\1\.sonarqube\out\.sonar\.sonartmp\7956119935354822877.tmp --config C:\Sonarqube_tslint\tslint.json ...
2016-12-09T12:51:53.3882025Z 13:51:53.185 DEBUG: Executing TsLint with command: node C:\Users\svctestmediaportal\AppData\Roaming\npm\node_modules\tslint\bin\tslint --format json --out C:\TfsAgent\_work\1\.sonarqube\out\.sonar\.sonartmp\7956119935354822877.tmp --config C:\Sonarqube_tslint\tslint.json ...
2016-12-09T12:51:53.6069605Z 13:51:53.419 DEBUG: Executing TsLint with command: node C:\Users\svctestmediaportal\AppData\Roaming\npm\node_modules\tslint\bin\tslint --format json --out C:\TfsAgent\_work\1\.sonarqube\out\.sonar\.sonartmp\7956119935354822877.tmp --config C:\Sonarqube_tslint\tslint.json ...
2016-12-09T12:51:53.8257180Z 13:51:53.622 DEBUG: Executing TsLint with command: node C:\Users\svctestmediaportal\AppData\Roaming\npm\node_modules\tslint\bin\tslint --format json --out C:\TfsAgent\_work\1\.sonarqube\out\.sonar\.sonartmp\7956119935354822877.tmp --config C:\Sonarqube_tslint\tslint.json ...
2016-12-09T12:51:54.0444818Z 13:51:53.841 DEBUG: Executing TsLint with command: node C:\Users\svctestmediaportal\AppData\Roaming\npm\node_modules\tslint\bin\tslint --format json --out C:\TfsAgent\_work\1\.sonarqube\out\.sonar\.sonartmp\7956119935354822877.tmp --config C:\Sonarqube_tslint\tslint.json ...
2016-12-09T12:51:54.2632362Z 13:51:54.044 DEBUG: Executing TsLint with command: node C:\Users\svctestmediaportal\AppData\Roaming\npm\node_modules\tslint\bin\tslint --format json --out C:\TfsAgent\_work\1\.sonarqube\out\.sonar\.sonartmp\7956119935354822877.tmp --config C:\Sonarqube_tslint\tslint.json ...
2016-12-09T12:51:54.4820006Z 13:51:54.278 DEBUG: Executing TsLint with command: node C:\Users\svctestmediaportal\AppData\Roaming\npm\node_modules\tslint\bin\tslint --format json --out C:\TfsAgent\_work\1\.sonarqube\out\.sonar\.sonartmp\7956119935354822877.tmp --config C:\Sonarqube_tslint\tslint.json ...
2016-12-09T12:51:54.7007581Z 13:51:54.513 DEBUG: Executing TsLint with command: node C:\Users\svctestmediaportal\AppData\Roaming\npm\node_modules\tslint\bin\tslint --format json --out C:\TfsAgent\_work\1\.sonarqube\out\.sonar\.sonartmp\7956119935354822877.tmp --config C:\Sonarqube_tslint\tslint.json ...
2016-12-09T12:51:54.9195105Z 13:51:54.732 DEBUG: Executing TsLint with command: node C:\Users\svctestmediaportal\AppData\Roaming\npm\node_modules\tslint\bin\tslint --format json --out C:\TfsAgent\_work\1\.sonarqube\out\.sonar\.sonartmp\7956119935354822877.tmp --config C:\Sonarqube_tslint\tslint.json ...
2016-12-09T12:51:55.1382796Z 13:51:54.935 DEBUG: Executing TsLint with command: node C:\Users\svctestmediaportal\AppData\Roaming\npm\node_modules\tslint\bin\tslint --format json --out C:\TfsAgent\_work\1\.sonarqube\out\.sonar\.sonartmp\7956119935354822877.tmp --config C:\Sonarqube_tslint\tslint.json ...
2016-12-09T12:51:55.3570278Z 13:51:55.169 DEBUG: Executing TsLint with command: node C:\Users\svctestmediaportal\AppData\Roaming\npm\node_modules\tslint\bin\tslint --format json --out C:\TfsAgent\_work\1\.sonarqube\out\.sonar\.sonartmp\7956119935354822877.tmp --config C:\Sonarqube_tslint\tslint.json ...
2016-12-09T12:51:55.5757874Z 13:51:55.388 DEBUG: Executing TsLint with command: node C:\Users\svctestmediaportal\AppData\Roaming\npm\node_modules\tslint\bin\tslint --format json --out C:\TfsAgent\_work\1\.sonarqube\out\.sonar\.sonartmp\7956119935354822877.tmp --config C:\Sonarqube_tslint\tslint.json ...
2016-12-09T12:51:55.7945442Z 13:51:55.607 DEBUG: Executing TsLint with command: node C:\Users\svctestmediaportal\AppData\Roaming\npm\node_modules\tslint\bin\tslint --format json --out C:\TfsAgent\_work\1\.sonarqube\out\.sonar\.sonartmp\7956119935354822877.tmp --config C:\Sonarqube_tslint\tslint.json ...
2016-12-09T12:51:56.0133035Z 13:51:55.810 DEBUG: Executing TsLint with command: node C:\Users\svctestmediaportal\AppData\Roaming\npm\node_modules\tslint\bin\tslint --format json --out C:\TfsAgent\_work\1\.sonarqube\out\.sonar\.sonartmp\7956119935354822877.tmp --config C:\Sonarqube_tslint\tslint.json ...
2016-12-09T12:51:56.2322505Z 13:51:56.029 DEBUG: Executing TsLint with command: node C:\Users\svctestmediaportal\AppData\Roaming\npm\node_modules\tslint\bin\tslint --format json --out C:\TfsAgent\_work\1\.sonarqube\out\.sonar\.sonartmp\7956119935354822877.tmp --config C:\Sonarqube_tslint\tslint.json ...
2016-12-09T12:51:56.4508213Z 13:51:56.232 DEBUG: Executing TsLint with command: node C:\Users\svctestmediaportal\AppData\Roaming\npm\node_modules\tslint\bin\tslint --format json --out C:\TfsAgent\_work\1\.sonarqube\out\.sonar\.sonartmp\7956119935354822877.tmp --config C:\Sonarqube_tslint\tslint.json ...
2016-12-09T12:51:56.6695814Z 13:51:56.450 DEBUG: Executing TsLint with command: node C:\Users\svctestmediaportal\AppData\Roaming\npm\node_modules\tslint\bin\tslint --format json --out C:\TfsAgent\_work\1\.sonarqube\out\.sonar\.sonartmp\7956119935354822877.tmp --config C:\Sonarqube_tslint\tslint.json ...
2016-12-09T12:51:56.8883335Z 13:51:56.763 INFO: ------------------------------------------------------------------------
2016-12-09T12:51:56.8883335Z 13:51:56.763 INFO: EXECUTION FAILURE
2016-12-09T12:51:56.8883335Z 13:51:56.763 INFO: ------------------------------------------------------------------------
2016-12-09T12:51:56.8883335Z 13:51:56.763 INFO: Total time: 29.486s
2016-12-09T12:51:57.1070973Z 13:51:56.966 INFO: Final Memory: 45M/304M
2016-12-09T12:51:57.1070973Z 13:51:56.966 INFO: ------------------------------------------------------------------------
2016-12-09T12:51:57.1070973Z ##[error]13:51:56.966 ERROR: Error during SonarQube Scanner execution
2016-12-09T12:51:57.1070973Z ##[error]java.lang.NullPointerException
2016-12-09T12:51:57.1070973Z ##[error]at com.pablissimo.sonar.TsLintParserImpl.parse(TsLintParserImpl.java:26)
2016-12-09T12:51:57.1070973Z ##[error]at com.pablissimo.sonar.TsLintSensor.execute(TsLintSensor.java:104)
2016-12-09T12:51:57.1070973Z ##[error]at org.sonar.scanner.sensor.SensorWrapper.analyse(SensorWrapper.java:53)
2016-12-09T12:51:57.1070973Z ##[error]at org.sonar.scanner.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:57)
2016-12-09T12:51:57.1070973Z ##[error]at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:49)
2016-12-09T12:51:57.1070973Z ##[error]at org.sonar.scanner.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:78)
2016-12-09T12:51:57.1070973Z ##[error]at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:182)
2016-12-09T12:51:57.1070973Z ##[error]at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
2016-12-09T12:51:57.1070973Z ##[error]at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
2016-12-09T12:51:57.1070973Z ##[error]at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:247)
2016-12-09T12:51:57.1070973Z ##[error]at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:242)
2016-12-09T12:51:57.1070973Z ##[error]at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:240)
2016-12-09T12:51:57.1070973Z ##[error]at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:232)
2016-12-09T12:51:57.1070973Z ##[error]at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
2016-12-09T12:51:57.1070973Z ##[error]at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
2016-12-09T12:51:57.1070973Z ##[error]at org.sonar.scanner.task.ScanTask.execute(ScanTask.java:47)
2016-12-09T12:51:57.1227207Z ##[error]at org.sonar.scanner.task.TaskContainer.doAfterStart(TaskContainer.java:86)
2016-12-09T12:51:57.1227207Z ##[error]at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
2016-12-09T12:51:57.1227207Z ##[error]at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
2016-12-09T12:51:57.1227207Z ##[error]at org.sonar.scanner.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:115)
2016-12-09T12:51:57.1227207Z ##[error]at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:118)
2016-12-09T12:51:57.1227207Z ##[error]at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:62)
2016-12-09T12:51:57.1227207Z ##[error]at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2016-12-09T12:51:57.1227207Z ##[error]at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
2016-12-09T12:51:57.1227207Z ##[error]at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
2016-12-09T12:51:57.1227207Z ##[error]at java.lang.reflect.Method.invoke(Unknown Source)
2016-12-09T12:51:57.1227207Z ##[error]at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
2016-12-09T12:51:57.1227207Z ##[error]at com.sun.proxy.$Proxy0.execute(Unknown Source)
2016-12-09T12:51:57.1227207Z ##[error]at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:233)
2016-12-09T12:51:57.1227207Z ##[error]at org.sonarsource.scanner.api.EmbeddedScanner.runAnalysis(EmbeddedScanner.java:151)
2016-12-09T12:51:57.1227207Z ##[error]at org.sonarsource.scanner.cli.Main.runAnalysis(Main.java:110)
2016-12-09T12:51:57.1227207Z ##[error]at org.sonarsource.scanner.cli.Main.execute(Main.java:74)
2016-12-09T12:51:57.1227207Z ##[error]at org.sonarsource.scanner.cli.Main.main(Main.java:61)
2016-12-09T12:51:57.1227207Z ##[error]13:51:56.966 ERROR:
2016-12-09T12:51:57.1227207Z ##[error]13:51:56.966 ERROR: Re-run SonarQube Scanner using the -X switch to enable full debug logging.
2016-12-09T12:51:57.4664813Z Process returned exit code 1
2016-12-09T12:51:57.4664813Z ##[error]The SonarQube Scanner did not complete successfully
2016-12-09T12:51:57.4664813Z 13:51:57.403  Creating a summary markdown file...
2016-12-09T12:51:57.4664813Z ##[error]Post-processing failed. Exit code: 1
2016-12-09T12:51:57.4821073Z ##[error]Unexpected exit code received from batch file: 1
2016-12-09T12:51:57.5133626Z The build was not set to fail if the associated quality gate fails.
```

Following versions are in use:
- TFS 2015 Update 3
- SonarTsPlugin v0.96-pre
- TSLint 4.0.2
- SonarQube v6.1

However, one strange observation is, that when running the SonarQube Scanner for MSBuild directly on the TFS build machine, the analysis is completed successfully.

I also tried switching to an older version of TSLint, but the error didn't go away.

**Comment by Pablissimo** [comment]
Can you try switching to an older version of the plugin? Wondering if I've missed a case with the recent changes to support TsLint 4.0.2 and other changes around supporting bits of Linux that were causing trouble.

**Comment by Pablissimo** [comment]
Just setup a build that's not (hopefully) radically dissimilar with this test project:

https://sonar.pablissimo.com/overview?id=22384

- Visual Studio Team Services build (so something not radically dissimilar to TFS 2015 Update 3)
- SonarTsPlugin v0.96-pre running on Linux (sonar.pablissimo.com)
- TSLint 4.0.2
- SonarQube 5.6.1

That worked at least, need to upgrade sonar.pablissimo.com to SQ 6.1 to check again.

Is there maybe a permissions issue with the build agent user not having read/write to the SonarQube temp folder? Would seem odd, there's exception handling in there to log that kind of error, but it's maybe worth checking?

**Comment by FourSpotProject** [comment]
Unbelievable, your guess with the permissions was right. When executing SonarQube Scanner for MSBuild I used a different account. Now everything is working fine.
Thanks!

**Comment by Pablissimo** [comment]
Hooray! Sorry it broke - to fix an issue on Linux it became necessary to write the ```tslint``` output to a temporary file and re-read it, rather than just stream its output via stdout. As a result the scanner now needs write privs on that temporary folder, so this is probably a break as a result of v0.96.

Still - glad you're sorted!

**Comment by NikitaEgorov** [comment]
I have same issue too (after update to Sonar 6.2)

```13:59:48.986 ERROR: Error during SonarQube Scanner execution
java.lang.NullPointerException
at com.pablissimo.sonar.TsLintParserImpl.parse(TsLintParserImpl.java:26)
at com.pablissimo.sonar.TsLintSensor.execute(TsLintSensor.java:104)
at org.sonar.scanner.sensor.SensorWrapper.analyse(SensorWrapper.java:53)
at org.sonar.scanner.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:57)
at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:49)
at org.sonar.scanner.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:78)
at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:182)
at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:247)
at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:242)
at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:240)
at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:232)
at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
at org.sonar.scanner.task.ScanTask.execute(ScanTask.java:47)
at org.sonar.scanner.task.TaskContainer.doAfterStart(TaskContainer.java:86)
at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
at org.sonar.scanner.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:115)
at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:116)
at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:62)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
at com.sun.proxy.$Proxy0.execute(Unknown Source)
at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:233)
at org.sonarsource.scanner.api.EmbeddedScanner.runAnalysis(EmbeddedScanner.java:151)
at org.sonarsource.scanner.cli.Main.runAnalysis(Main.java:110)
at org.sonarsource.scanner.cli.Main.execute(Main.java:74)
at org.sonarsource.scanner.cli.Main.main(Main.java:61)```
