### ISSUE TITLE
Error during SonarQube Scanner Execution

### ISSUE THREAD

**Issue by alexrun** [Pablissimo/SonarTsPlugin#86]
Hello, I'm testing the coverage of an angular-cli proyect. After assigning the sonar.ts.lcov.reportpath param and executing sonar scanner I get an InvalidPathException.

**19:46:19.522 ERROR: Error during SonarQube Scanner execution java.nio.file.InvalidPathException: Illegal char <:> at index 123: C:\Users\acastaneda\Documents\workspace-sts-3.8.3.RELEASE\FrontEndTemplate\node_modules\angular2-template-loader\index.js!C:\Users\acastaneda\Documents\workspace-sts-3.8.3.RELEASE\FrontEndTemplate\src\test.ts**
        at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
        at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
        at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
        at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
        at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
        at java.io.File.toPath(File.java:2234)
        at org.sonar.api.scan.filesystem.PathResolver.relativePath(PathResolver.java:95)
        at org.sonar.api.batch.fs.internal.AbsolutePathPredicate.get(AbsolutePathPredicate.java:52)
        at org.sonar.api.batch.fs.internal.DefaultFileSystem.inputFiles(DefaultFileSystem.java:164)
        at org.sonar.api.batch.fs.internal.DefaultFileSystem.inputFile(DefaultFileSystem.java:124)
        **at com.pablissimo.sonar.LCOVParserImpl.loadCurrentFileData(LCOVParserImpl.java:152)
        at com.pablissimo.sonar.LCOVParserImpl.parse(LCOVParserImpl.java:104)
        at com.pablissimo.sonar.LCOVParserImpl.<init>(LCOVParserImpl.java:59)
        at com.pablissimo.sonar.LCOVParserImpl.create(LCOVParserImpl.java:72)
        at com.pablissimo.sonar.TsCoverageSensorImpl.getParser(TsCoverageSensorImpl.java:106)
        at com.pablissimo.sonar.TsCoverageSensorImpl.saveMeasureFromLCOVFile(TsCoverageSensorImpl.java:81)
        at com.pablissimo.sonar.TsCoverageSensorImpl.execute(TsCoverageSensorImpl.java:141)
        at com.pablissimo.sonar.CombinedCoverageSensor.execute(CombinedCoverageSensor.java:34)**
        at org.sonar.scanner.sensor.SensorWrapper.analyse(SensorWrapper.java:53)
        at org.sonar.scanner.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:57)
        at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:49)
        at org.sonar.scanner.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:78)
        at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:182)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
        at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:247)
        at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:242)
        at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:232)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
        at org.sonar.scanner.task.ScanTask.execute(ScanTask.java:47)
        at org.sonar.scanner.task.TaskContainer.doAfterStart(TaskContainer.java:86)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
        at org.sonar.scanner.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:115)
        at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:116)
        at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:62)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
        at com.sun.proxy.$Proxy0.execute(Unknown Source)
        at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:233)
        at org.sonarsource.scanner.api.EmbeddedScanner.runAnalysis(EmbeddedScanner.java:151)
        at org.sonarsource.scanner.cli.Main.runAnalysis(Main.java:110)
        at org.sonarsource.scanner.cli.Main.execute(Main.java:74)
        at org.sonarsource.scanner.cli.Main.main(Main.java:61)

**Comment by alexrun** [comment]
This is how my sonar-proyect.properties looks like:

`sonar.projectKey=Template`
`sonar.projectName=Template`
`sonar.projectVersion=1.0.0`
`sonar.sources=src/app`
`sonar.sourceEncoding=UTF-8`
`sonar.exclusions=**/node_modules/**,**/*.spec.ts`
`sonar.tests=src/app`
`sonar.test.inclusions=**/*.spec.ts`
`sonar.ts.lcov.reportpath=coverage/coverage.lcov`
`sonar.ts.tslintconfigpath=tslint.json`

**Comment by alexrun** [comment]
I have a case like the **src/test/resources/lcov/angular.lcov** file, in wich the source file is represented as 

S**F:path/to/template/loader.js!path/to/file.ts**

**SF:C:/Users/acastaneda/Documents/workspace-sts-3.8.3.RELEASE/FrontEndTemplate/node_modules\angular2-template-loader\index.js!C:\Users\acastaneda\Documents\workspace-sts-3.8.3.RELEASE\FrontEndTemplate\src\test.ts**

It looks like doesn't recognize the second colon.

**Comment by Pablissimo** [comment]
Oh, that's a bit exciting - will create a test case for it and fix, if possible (it's odd that you've got two kinds of path separators in the same SF: line so maybe I need to be doing some canonicalisation before trying to process things further).

At NDC just now though, so may be unable to fix this week (unless the hotel WiFi's started letting SSH connections through which it actively didn't last year...)

**Comment by Pablissimo** [comment]
Can you confirm what version of the following you're running please?
- Either sonar-scanner or sonar-runner (whatever you're using)
- SonarQube itself

I think I know what the issue *is*, I just can't reproduce it locally. Will keep trying to break my local install...

**Comment by alexrun** [comment]
Hello Pablissimo, this is the environment I'm currently working with:

SonarQube Scanner 2.8
SonarQube 6.2
Windows Server 2012

When I test my project in a Debian OS it works without problems because the path doesn't have colons, but I stil get a path with two parts splited by an exclamation mark...

**Comment by alexrun** [comment]
Hello Pablissimo, this is the environment I'm currently working with:

SonarQube Scanner 2.8
SonarQube 6.2
Windows Server 2012

When I test my project in a Debian OS it works without problems because the path doesn't have colons, but I stil get a path with two parts splited by an exclamation mark...

**Comment by Pablissimo** [comment]
Brill, thanks - same/close enough to my eventual test environment that I'm pretty happy with the fix. So the exclamation mark shouldn't matter (there's logic in the LCOV parser now to split the path on exclamation marks if it fails to resolve the first time), but the process is basically:

- Try and find the file in the analysis set that the SF line refers to
- If it doesn't map to anything, and it contains an exclamation mark then split on that and try the second half of the line

On Linux that works fine, because the path when taken as a whole is nonsense but at least *valid*, in terms of the file system (/path/to/angular.js!/path/to/something/else/real). On Windows the equivalent string isn't even a valid path, since it has two colons in it so it detonates on the first check.

If you're capable of building the project you're welcome to build off the issue86 branch which should have a fix for you, otherwise it'll need to wait until I do a bit of merging and figure out how the heck to refer to the next version without going 1.0 on it (since I was saving that for when the configuration options are all tidied up, as it'll be a horribly breaking change \o/)

**Comment by Pablissimo** [comment]
[sonar-typescript-plugin-0.99.1-SNAPSHOT.zip](https://github.com/Pablissimo/SonarTsPlugin/files/715212/sonar-typescript-plugin-0.99.1-SNAPSHOT.zip)

Candidate for, and I can't believe I'm writing this as a version string, v0.99.1 with the above fix. Let me know how you get on!

**Comment by alexrun** [comment]
@Pablissimo, I  was able to test your fix today and it worked like a charm, congrats on fixing the bug. Your angularwindowspaths.lcov resource file looks pretty much like my path file and your changes to the LCOVParserImpl class caught the InvalidPathException exception without a problem. Thanks for the hard work you are doing. 

I would like to ask why you didn't want to use the Semantic Versioning?

**Comment by Pablissimo** [comment]
Will be using from 1.0 since it'll have refreshed property names, mostly inertia!


-------- Original message --------

**Comment by manasarajaluri** [comment]
i am using java-8 version and jenkins 2.121.1 version,sonarqube 6.7 version and installed both the sonarqube and jenkins on same server.when integrating sonarqube with jenkins the below issue is being raised.
ERROR: Error during SonarQube Scanner execution
org.sonarsource.scanner.api.internal.ScannerException: Unable to execute SonarQube
	at org.sonarsource.scanner.api.internal.IsolatedLauncherFactory$1.run(IsolatedLauncherFactory.java:84)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherFactory$1.run(IsolatedLauncherFactory.java:71)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherFactory.createLauncher(IsolatedLauncherFactory.java:71)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherFactory.createLauncher(IsolatedLauncherFactory.java:67)
	at org.sonarsource.scanner.api.EmbeddedScanner.doStart(EmbeddedScanner.java:218)
	at org.sonarsource.scanner.api.EmbeddedScanner.start(EmbeddedScanner.java:156)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:74)
	at org.sonarsource.scanner.cli.Main.main(Main.java:61)
Caused by: java.lang.IllegalStateException: Fail to bootstrap from server. Bootstrap index was:
<!DOCTYPE html><html lang="en"><head><meta http-equiv="content-type" content="text/html; charset=UTF-8" charset="UTF-8"/><meta http-equiv="X-UA-Compatible" content="IE=edge"><link rel="apple-touch-icon" href="/apple-touch-icon.png"><link rel="apple-touch-icon" sizes="57x57" href="/apple-touch-icon-57x57.png"><link rel="apple-touch-icon" sizes="60x60" href="/apple-touch-icon-60x60.png"><link rel="apple-touch-icon" sizes="72x72" href="/apple-touch-icon-72x72.png"><link rel="apple-touch-icon" sizes="76x76" href="/apple-touch-icon-76x76.png"><link rel="apple-touch-icon" sizes="114x114" href="/apple-touch-icon-114x114.png"><link rel="apple-touch-icon" sizes="120x120" href="/apple-touch-icon-120x120.png"><link rel="apple-touch-icon" sizes="144x144" href="/apple-touch-icon-144x144.png"><link rel="apple-touch-icon" sizes="152x152" href="/apple-touch-icon-152x152.png"><link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon-180x180.png"><link rel="icon" type="image/x-icon" href="/favicon.ico"><meta name="application-name" content="SonarQube"/><meta name="msapplication-TileColor" content="#FFFFFF"/><meta name="msapplication-TileImage" content="/mstile-512x512.png"/><link href="/css/sonar.b06ee6ee.css" rel="stylesheet"><title>SonarQube</title></head><body><div id="content"><div class="global-loading"><i class="spinner global-loading-spinner"></i> <span class="global-loading-text">Loading...</span></div></div><script>window.baseUrl=""</script><script src="/js/vendor.017c6e7f.js"></script><script src="/js/app.b06ee6ee.js"></script></body></html>
	at org.sonarsource.scanner.api.internal.Jars.getScannerEngineFiles(Jars.java:88)
	at org.sonarsource.scanner.api.internal.Jars.download(Jars.java:70)
	at org.sonarsource.scanner.api.internal.JarDownloader.download(JarDownloader.java:39)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherFactory$1.run(IsolatedLauncherFactory.java:75)
	... 8 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
	at org.sonarsource.scanner.api.internal.Jars.getScannerEngineFiles(Jars.java:84)
	... 11 more
