### ISSUE TITLE
Latest master branch doesn't build

### ISSUE THREAD

**Issue by afterbangx** [Pablissimo/SonarTsPlugin#95]
Hello, 

I'm experiencing the issue mentioned [here](https://github.com/Pablissimo/SonarTsPlugin/issues/49). I've tried cloning the latest from master and building but there are some tests failing that are preventing a build. I'm going to try to dig in and fix them but I'm not familiar enough with what's happening here to know what the right solution is. Could you please take a look. Also, I wasn't sure if I am doing something wrong that's causing these failures or if you were aware this was even happening. Thanks!

```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running com.pablissimo.sonar.CombinedCoverageSensorTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.526 sec - in com.pablissimo.sonar.CombinedCoverageSensorTest
Running com.pablissimo.sonar.LCOVParserImplTest
WARN  Problem during processing LCOV report: can't save DA data for line 0 (Line with number 0 doesn't belong to file path/to/file.ts).
WARN  Problem during processing LCOV report: can't save DA data for line 4 (Line with number 4 doesn't belong to file path/to/file.ts).
WARN  Problem during processing LCOV report: can't save DA data for line 0 (Line with number 0 doesn't belong to file path/to/file.ts).
WARN  Problem during processing LCOV report: can't save DA data for line 4 (Line with number 4 doesn't belong to file path/to/file.ts).
Tests run: 9, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.075 sec - in com.pablissimo.sonar.LCOVParserImplTest
Running com.pablissimo.sonar.LOCSensorImplTest
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.022 sec - in com.pablissimo.sonar.LOCSensorImplTest
Running com.pablissimo.sonar.model.TsLintConfigTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec - in com.pablissimo.sonar.model.TsLintConfigTest
Running com.pablissimo.sonar.model.TsLintIssueTest
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec - in com.pablissimo.sonar.model.TsLintIssueTest
Running com.pablissimo.sonar.model.TsLintPositionTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec - in com.pablissimo.sonar.model.TsLintPositionTest
Running com.pablissimo.sonar.model.TsLintRuleTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec - in com.pablissimo.sonar.model.TsLintRuleTest
Running com.pablissimo.sonar.PathResolverImplTest
Tests run: 6, Failures: 3, Errors: 0, Skipped: 0, Time elapsed: 0.003 sec <<< FAILURE! - in com.pablissimo.sonar.PathResolverImplTest
returnsAbsolutePathToFallbackFile_ifPrimaryNotConfiguredButEmptyAndFallbackExists(com.pablissimo.sonar.PathResolverImplTest)  Time elapsed: 0.001 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<[c]:\SonarTsPlugin\targ...> but was:<[C]:\SonarTsPlugin\targ...>
        at com.pablissimo.sonar.PathResolverImplTest.returnsAbsolutePathToFallbackFile_ifPrimaryNotConfiguredButEmptyAndFallbackExists(PathResolverImplTest.java:55)

returnsAbsolutePathToFile_ifSpecifiedAndExists(com.pablissimo.sonar.PathResolverImplTest)  Time elapsed: 0 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<[c]:\SonarTsPlugin\targ...> but was:<[C]:\SonarTsPlugin\targ...>
        at com.pablissimo.sonar.PathResolverImplTest.returnsAbsolutePathToFile_ifSpecifiedAndExists(PathResolverImplTest.java:42)

returnsAbsolutePathToFallbackFile_ifPrimaryNotConfiguredAndFallbackExists(com.pablissimo.sonar.PathResolverImplTest)  Time elapsed: 0.001 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<[c]:\SonarTsPlugin\targ...> but was:<[C]:\SonarTsPlugin\targ...>
        at com.pablissimo.sonar.PathResolverImplTest.returnsAbsolutePathToFallbackFile_ifPrimaryNotConfiguredAndFallbackExists(PathResolverImplTest.java:48)

Running com.pablissimo.sonar.TsCoverageSensorImplTest
Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.354 sec - in com.pablissimo.sonar.TsCoverageSensorImplTest
Running com.pablissimo.sonar.TsLintExecutorConfigTest
Tests run: 10, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.009 sec - in com.pablissimo.sonar.TsLintExecutorConfigTest
Running com.pablissimo.sonar.TsLintExecutorImplTest
Tests run: 8, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.119 sec - in com.pablissimo.sonar.TsLintExecutorImplTest
Running com.pablissimo.sonar.TsLintParserTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.043 sec - in com.pablissimo.sonar.TsLintParserTest
Running com.pablissimo.sonar.TsLintSensorTest
Tests run: 15, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.053 sec - in com.pablissimo.sonar.TsLintSensorTest
Running com.pablissimo.sonar.TsRulesDefinitionTest
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.217 sec - in com.pablissimo.sonar.TsRulesDefinitionTest
Running com.pablissimo.sonar.TypeScriptLanguageTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.002 sec - in com.pablissimo.sonar.TypeScriptLanguageTest
Running com.pablissimo.sonar.TypeScriptPluginTest
Tests run: 10, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.004 sec - in com.pablissimo.sonar.TypeScriptPluginTest
Running com.pablissimo.sonar.TypeScriptRuleProfileTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.002 sec - in com.pablissimo.sonar.TypeScriptRuleProfileTest

Results :

Failed tests:
  PathResolverImplTest.returnsAbsolutePathToFallbackFile_ifPrimaryNotConfiguredAndFallbackExists:48 expected:<[c]:\SonarTsPlugin\targ...> but was:<[C]:\SonarTsPlugin\targ...>
  PathResolverImplTest.returnsAbsolutePathToFallbackFile_ifPrimaryNotConfiguredButEmptyAndFallbackExists:55 expected:<[c]:\SonarTsPlugin\targ...> but was:<[C]:\SonarTsPlugin\targ...>
  PathResolverImplTest.returnsAbsolutePathToFile_ifSpecifiedAndExists:42 expected:<[c]:\SonarTsPlugin\targ...> but was:<[C]:\SonarTsPlugin\targ...>

Tests run: 102, Failures: 3, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.931 s
[INFO] Finished at: 2017-01-30T09:37:19-06:00
[INFO] Final Memory: 10M/25M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project sonar-typescript-plugin: There are test failures.
[ERROR]
[ERROR] Please refer to c:\SonarTsPlugin\target\surefire-reports for the individual test results.
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project sonar-typescript-plugin: There are test failures.

Please refer to c:\SonarTsPlugin\target\surefire-reports for the individual test results.
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoFailureException: There are test failures.

Please refer to c:\SonarTsPlugin\target\surefire-reports for the individual test results.
        at org.apache.maven.plugin.surefire.SurefireHelper.reportExecution(SurefireHelper.java:91)
        at org.apache.maven.plugin.surefire.SurefirePlugin.handleSummary(SurefirePlugin.java:320)
        at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:892)
        at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:755)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        ... 20 more```

**Comment by Pablissimo** [comment]
Can you let me know your OS version, please? That's an odd one - I develop on Windows 10 and haven't see the above, but I notice there's a fix for the test in a PR knocking about that I need to apply.

**Comment by afterbangx** [comment]
I'm also on Windows 10. I also saw the the PR with the tests that have been fixed this morning. I think it's [here](https://github.com/Pablissimo/SonarTsPlugin/pull/93)

**Comment by Pablissimo** [comment]
That PR's been merged into master, so hopefully you should be able to build fine now. It's odd - it's something I never encountered and I build on both Windows and Linux. Anyhoo!
